shared: &shared
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 5

development:
  <<: *shared
  database: <%= $globals.app.underscore %>_<%= $globals.user %>_development

production:
  <<: *shared
  database: <%= $globals.app.underscore %>

sandbox:
  <<: *shared
  database: <%= $globals.app.underscore %>_sandbox

test:
  <<: *shared
  database: <%= $globals.app.underscore %>_<%= $globals.user %>_test
